# Generated by Django 6.0.6 on 2026-06-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
    ]
