# Generated by Django 6.0.6 on 2026-06-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
