# Generated by Django 6.0.6 on 2026-06-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
