# Generated by Django 6.0.6 on 2026-07-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='role',
            field=models.CharField(default='Recruiter', max_length=20),
        ),
    ]
