# Generated by Django 6.0.6 on 2026-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='role',
            field=models.CharField(default='Candidate', max_length=20),
        ),
    ]
